### PR TITLE
#106

### PR DESCRIPTION
**Pull request by jindai1783**
fix for #106

### CODE REVIEW

**Comment by masumsoft** [comment]
Cool! could you please add some tests for multiple orderby? I guess you might need to add a new model in the tests to properly test orderby clauses.

**Comment by jindai1783** [comment]
We need a bit help on that, because we've tried to run the tests but they are failing (they failed before doing the change).

This is our issue:
```
  Unit Tests
    #modelsync
      1) should connect and sync with db without errors


  0 passing (748ms)
  1 failing

  1) Unit Tests #modelsync should connect and sync with db without errors:
     apollo.model.tablecreation.dbindexcreate: Error while creating index on DB Table -> ResponseError: Unable to find custom indexer class 'com.stratio.cassandra.lucene.Index'
      at f (../../src/orm/apollo_error.js:170:17)
      at ../../src/orm/base_model.js:468:30
      at node_modules/async/lib/async.js:52:16
      at node_modules/async/lib/async.js:264:21
      at node_modules/async/lib/async.js:44:16
      at ../../src/orm/base_model.js:463:31
      at next (node_modules/cassandra-driver/lib/utils.js:713:14)
      at RequestHandler._handleError (node_modules/cassandra-driver/lib/request-handler.js:307:12)
      at readCallback (node_modules/cassandra-driver/lib/request-handler.js:185:19)
      at Connection.invokeCallback (node_modules/cassandra-driver/lib/connection.js:612:5)
```

Any ideas?

**Comment by masumsoft** [comment]
Oh! The tests contain custom indexes that are not directly shipped with standard cassandra, we test the custom indexes using the cassandra-lucene-index plugin. You can download the pre configured cassandra version that we use for travis builds to run tests successfully: https://www.dropbox.com/s/f86zyi3qmhqvfbp/apache-cassandra-3.9.tar.gz

**Comment by jindai1783** [comment]
Perfect, that worked! Give us few minutes to do the test cases.

**Comment by jindai1783** [comment]
Can you help us a bit about the linting? It breaks because of code duplication but I have to do it in order to create the use cases. Also, I am running the linter locally and I don't have the same linting issues. How can I run it and get the same results as in the code climate?

**Comment by masumsoft** [comment]
Let's not get much worried about codeclimate issues now, I would like to get a refresh on code duplication in the whole project later on, there are many areas that can be improved in the codebase and if I get time, I have plans to improve overall test coverage and coldeclimate ranks in a later version.

I'll have a look at this and possibly merge this PR in short time.

**Comment by jindai1783** [comment]
Sounds good, thanks for publishing the update, all sorted!

**Pull request merged**
